### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by michaelzoidl** [entwicklerstube/babel-plugin-root-import#104]
I think a lot of people already noticed that this project is not that maintained, thats the reason why I'am calling you, if you're using this project and want to update / maintain this just write in this chat.

I give you:
- Rights to merge pull requests
- Rights to npm to publish new versions
- A note in the README that you're the maintainer of this project

Hope we find someone who has more time than me to improve this project!

Thanks

Michael

**Comment by brigand** [comment]
I'm happy to maintain this project. I use it regularly and I have a few babel plugins of my own.

**Comment by brigand** [comment]
Hey, could you go ahead and add me as a collaborator? It's much easier to work on this when I can close issues as they're resolved.
