### ISSUE TITLE
Using slashed in root prefix

### ISSUE THREAD

**Issue by vihanb** [entwicklerstube/babel-plugin-root-import#108]
My documentation generator (which runs through this plugin) is not very smart so it is incorrectly processes `./models/Foo.js` as `./models/models/Foo.js` for example. I have no idea why this is happening (issue with my docgen not this plugin) but I was hoping I could fix this using:

```json
[
  {
    "rootPathPrefix": "~/models",
    "rootPathSuffix": "../../"
  },
  {
    "rootPathPrefix": "~",
    "rootPathSuffix": "../"
  }
]
```

however this doesn't seem to work. Is there a way to do something like this?

**Comment by brigand** [comment]
From the readme:

> ### Custom rootPathPrefix
> This *must* be 1 or 2 characters. Any additional characters are ignored.

If `rootPathSuffix` doesn't accept parent paths with `../`, that should be fixed.

I'm not sure about allowing longer `rootPathPrefix` strings. I don't immediately see any harm in it, but I'll look into it in the next few days.

Any thoughts on possible issues from either of these would be appreciated.

**Comment by MichaelBitard** [comment]
This PR lift the 2 characters restriction https://github.com/entwicklerstube/babel-plugin-root-import/pull/122

**Comment by brigand** [comment]
PR was merged
