### ISSUE TITLE
play nice with import/order

### ISSUE THREAD

**Issue by Fandekasp** [entwicklerstube/babel-plugin-root-import#119]
Related to https://github.com/benmosher/eslint-plugin-import/issues/795#issuecomment-444758032.

Would it be difficult to support the `import/order` rule so that it understand all `~/` imports as part of the same group (I suppose the **internal** one) ?

When I try the option `{"newlines-between": "always"}`, all groups are nicely grouped and separated by an empty line, except for all the `~/something` import, which aren't grouped and all separated by an empty line.
This results in something like following:
```es6
import React, {Component, Fragment} from "react";
import PropTypes from "prop-types";
import {Element} from "react-scroll";
import {Link} from "react-router-dom";
import {connect} from "react-redux";

import {withLogs, withMotion} from "~/lib/decorators";

import {imageUrlProp} from "~/lib/customProps";

import {getHostDetailsAction} from "~/actions";

import {getContactUrl} from "~/urls";

import Cta from "./Cta";
import BasicInfo from "./BasicInfo";
```

I would really appreciate if we could turn this as:
```es6
import React, {Component, Fragment} from "react";
import PropTypes from "prop-types";
import {Element} from "react-scroll";
import {Link} from "react-router-dom";
import {connect} from "react-redux";

import {withLogs, withMotion} from "~/lib/decorators";
import {imageUrlProp} from "~/lib/customProps";
import {getHostDetailsAction} from "~/actions";
import {getContactUrl} from "~/urls";

import Cta from "./Cta";
import BasicInfo from "./BasicInfo";
```

**Comment by lucasveigaf** [comment]
Seems like a lot of people would like something like this. Perhaps we could use a regex to define a new group?

**Comment by brigand** [comment]
Is there something we can do here? I'm not sure what the actionable part of this issue is.

**Comment by brigand** [comment]
Closing as this seems to be a feature request for a separate project, or a good idea for a new library.
