### ISSUE TITLE
error Unable to resolve module `@/Routers` from `src/App.tsx`: @/Routers could not be found within the project.

### ISSUE THREAD

**Issue by boonook** [entwicklerstube/babel-plugin-root-import#144]
typescript native版本：0.63.2   babel-plugin-root-import：0.65.8
xcode 11.7 
打包到ios的真机过程中报错 

babel.config.js  error Unable to resolve module `@/Routers` from `src/App.tsx`: @/Routers could not be found within the project.

![image](https://user-images.githubusercontent.com/34494413/98623165-13b14680-2346-11eb-9b8c-af5529e2d95e.png)

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      "babel-plugin-root-import",
      {
        rootPathSuffix: "./src",
        rootPathPrefix: "@/"
      }
    ]
  ]
};
```

tsconfig.json
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "jsx": "react",
    "allowSyntheticDefaultImports": true
  }
}
```

**Comment by boonook** [comment]
打dubug包没有问题，但是打正式包就报错

**Comment by brigand** [comment]
The babel config looks right. My guess is that your build system isn't running it through babel in the production build. It might be a problem specific to react-native + typescript.

I'm going to close this as it doesn't appear we can do anything on our end, but will reopen if that changes.

**Comment by boonook** [comment]
@brigand  请教一下我该如何处理呢？

**Comment by boonook** [comment]
已修复将以下内容从babel.config.js放到.babelrc
[
      "babel-plugin-root-import",{
        "rootPathSuffix": "./src",
        "rootPathPrefix": "@/"
      }
    ]
