### ISSUE TITLE
Cannot webpack-build when depending on a package that uses your plugin

### ISSUE THREAD

**Issue by meglio** [entwicklerstube/babel-plugin-root-import#146]
A package uses `babel-plugin-root-import` and lots of paths prefixed with `~`, for example: `~/base.scss`.

Now, when I use that package a dependency in my project, it throws an error:

```
Error: /xxx/node_modules/dependency_name/components/PageTemplate/index.js: Cannot find module '~/styles/common.scss'
```

I added `'babel-plugin-root-import'` plugin to my babel config file, but it did not help.

The question is, how do I webpack-build when depending on an npm package that uses your plugin?

**Comment by brigand** [comment]
You appear to be importing the source code. For packages using babel, they're expected to provide a directory with the babel output files. Those will have the `~` replaced with the correct relative path.

If you're not sure how to import the right files, or if the files aren't in the final package, please file an issue on $dependency_name.
