### ISSUE TITLE
Support for multichar string as rootPathPrefix

### ISSUE THREAD

**Issue by vedraan** [entwicklerstube/babel-plugin-root-import#43]
Great plugin. Would it be possible to enhance the rootPathPrefix option to accept multichar strings instead of only one character?

Example:

```
    plugins: [
        ['babel-root-import', [{
            'rootPathPrefix': 'CORE_PATH',
            'rootPathSuffix': 'core/app'
        }, {
            'rootPathPrefix': 'THEME_PATH',
            'rootPathSuffix': 'theme/app'
        }]]
    ]
```

Imports could look like this, which would be more readable to programmers that didn't write the code:
`import config from 'THEME_PATH/config/config.app';`

**Comment by michaelzoidl** [comment]
So you mean with multichar strings a prefix with more `/`?
If yes, it's difficult because this symbol is used by the detect function... 
maybe you could use a `.` instead?

`import config from 'THEME_PATH.config/config.app'`
`import config from 'THEME_PATH.controller/dummy'`
`import config from 'THEME_PATH.view/dummy'`

**Comment by vedraan** [comment]
Not really, anything more than one character didn't work for me, I tried:
```
'rootPathPrefix': 'THEME_PATH'
```
but when I tried importing like this
`import config from 'THEME_PATH/config/config.app';`

I got an error, can't find THEME_PATH/config/config.app module. No replacement happened.

Then I tried (which is what I'm using now):

```
'rootPathPrefix': '_'
```
and
`import config from '_/config/config.app';`
works fine.

So it seems anything more than one character as a prefix doesn't work. I didn't really try two or three letter words, but just assuming.

**Comment by sivael** [comment]
One character is better because ~/ is frequently used to denote user home directory and is easily transferrable to project home directory. 
If You see other weird characters (&, %, $, #, @, ^) at the beginning of the path it is obvious that someone is doing something weird there and will either ask or know it's in the babel-root-import library.
THEME_PATH looks like a constant, which it is not and would end up being confusing and cause errors.

**Comment by vedraan** [comment]
@sivael I would disagree on the THEME_PATH being any more confusing than single characters to anyone who doesn't know a project uses babel-root-import. You can't really use variables and constants in import/require statements, so I don't see how someone can confuse it for a constant, or how it could cause any errors.
I'm not suggesting replacing any default prefix values, however I don't see why they should be limited to only one character. I might get some free time next week to write up a PR for this.

**Comment by sivael** [comment]
I consider all capital underscored symbols to be constants, as those are used in a lot of places and languages this way, but if that's where You want to go and others don't mind, I guess it makes sense to include it unless there's collateral damage to performance and/or other parts of the system.

**Comment by pllee** [comment]
If this is not added as a feature I think it should explicitly documented that the prefix cannot be more than a single character or have a good runtime error message.  I tried using ```$src``` and I had no clue why it wasn't working and I thought it was a problem with my root postfix.

**Comment by vikfroberg** [comment]
Haven't tested it too much, but it seams like an easy fix. I'm using my fork for a project at the moment.
https://github.com/vikfroberg/babel-root-import/commit/800beabf7284fe2c69ad788d428e1f6f9a399512

**Comment by zheeeng** [comment]
Really wish this feature, in react native, I tried babel-plugin-module-alias and babel-plugin-module-resolver , they all disabled. Then I found root-import plugin works fine but only a single character is supported. May a feature improving in the next version?

**Comment by zheeeng** [comment]
https://github.com/tleunen/babel-plugin-module-resolver/issues/29 Discussed the problem that import-path-change plugin failure in RN.

**Comment by adrianmcli** [comment]
Even if this is not supported, I agree that there should be an error or at least something said about it inside the README file.

**Comment by bathos** [comment]
Also worth noting that the constraint doesn’t seem to be single character, but rather a single two byte code unit (probably being accessed unsafely with `[0]`?) Therefore, to my despair, this fails:

```
            {
              "rootPathPrefix": "🐍",
              "rootPathSuffix": "../snek"
            }
```

**Comment by brigand** [comment]
This is now supported, including at least single codepoint emojis.
