### ISSUE TITLE
imports fail when using babel-root-import

### ISSUE THREAD

**Issue by Fosol** [entwicklerstube/babel-plugin-root-import#55]
standard import statements for 3rd party dependency packages fail when using the babel-root-import package.

// Works without babel-root-import
// Fails when babel-root-import is configured to change rootPathSuffix.
import name from "package-name";

It appears to me that babel-root-import only works when importing your own local modules.

**Comment by sivael** [comment]
I have tested it and I see no issues while importing packages in any form.
Could You please provide a minimal example we could follow to reproduce the issue?

**Comment by michaelzoidl** [comment]
@Fosol can you give us more informations? Otherwise i will close this issue..

**Comment by Fosol** [comment]
Busy until Monday, sorry.

**Comment by Fosol** [comment]
npm install -D babel-root-import
---
.babelrc
```
{
    "presets": [
      "es2015"
    ],
    "plugins": [
      ["babel-root-import", {
        "rootPathSuffix": "src"
      }]
    ]
}
```
---
Folder/file structure
-src
--core
---type.js
--promise
---promise.js
---
promise.js
```
import {Types} from "~/core/type";
...
```
---
run command 'ava' to test.
It should be noted that the ava test files correctly use the babel-root-import, but all the modules that import (like the above example in promise.js) fail.
# Error
```
Error: Cannot find module '../src/core/type'
...
```
Is there any other information you need?

**Comment by AlecAivazis** [comment]
I'm also seeing an error when the source directory is `src` - we changed this to `src2` and it worked. I'm going to try to figure out what's going on and i'll report here when/if I have more info

**Comment by natew** [comment]
I'm also getting an error just like this. Going to try the `src` thing and see if that works.
