### ISSUE TITLE
System.import cannot use root import

### ISSUE THREAD

**Issue by andykais** [entwicklerstube/babel-plugin-root-import#60]
Hi, this code here `System.import('~/containers/page')` fails given this .babelrc

```
{
  "plugins": [
    "transform-react-jsx",
    "transform-strict-mode",
    "system-import-transformer",
    [
        "babel-root-import",
        {"rootPathSuffix": "client"}
    ]
  ],
  "presets": ["react", "es2015", "stage-2"] ,
  "env": {
      "development": {
        "presets": ["react-hmre"]
      }
  },
  ignore: ["/node_modules/"]
}
```

webpack reports this
```
Module not found: Error: Cannot resolve module '~/containers/page' in /home/user/project/client
```
however the old way, `System.import('./containers/page')` works just fine

**Comment by michaelzoidl** [comment]
Hi @andykais, 
ya currently we only support the "normal" `import` statement and the `require` function, so we don't support the `System.import` yet.

I would say this should be a *feature_request*, sadly i cannot promise when we support this :/

**Comment by andykais** [comment]
wowzers this is an old issue! I should say `System.import` is less relevant now. For people who want to use dynamic imports, the new [import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) syntax is the successor to `System.import` and is supported by this library.

given this source code:
```js
import x from '~/component/sample'
import('~/component/sample')
require('~/component/sample')
```
using this plugin it becomes:
```js
import x from './component/sample'
import('./component/sample')
require('./component/sample')
```

it may be worth adding to the README @brigand

**Comment by brigand** [comment]
Good idea. Tested that it still works and added it to the README.
