### ISSUE TITLE
Full path names?

### ISSUE THREAD

**Issue by azarus** [entwicklerstube/babel-plugin-root-import#62]
Hey,

I have a little issue with this package. When compiling with babel-cli the output packages get a full file path name.

When using: 
`
import "/Services/MyService";`

it produces:
`require("f:\\Coding\\Projects\\Website/source/Services/MyService");
`
And instead it should produce this.
`require("/Services/MyService");
`

**Comment by sivael** [comment]
/Services/MyService is a valid full path on linux and mac and thus is interpreted as such.
If You want relative paths, use 
Services/MyService
If You want project-relative paths use something along the lines of 
~/Services/MyService

I guess it's working as intended.

**Comment by azarus** [comment]
I posted it here since i can't open an issue for this:
https://github.com/mantrajs/babel-root-slash-import

**Comment by azarus** [comment]
Anyways, i ended up rolling my own that works well for both browser and nodejs. Based on this:
https://www.npmjs.com/package/babel-project-relative-import

**Comment by brigand** [comment]
I'm unable to check, but this most likely isn't an issue anymore.
