### ISSUE TITLE
More consistent name: babel-plugin-root-import

### ISSUE THREAD

**Issue by denysdovhan** [entwicklerstube/babel-plugin-root-import#63]
Hi! Thanks for awesome plugin!

Babel's docs say about [Plugin/Preset Shorthands](https://babeljs.io/docs/plugins/#plugin-preset-paths-plugin-preset-shorthand). Most of plugins works well with that shorthand notation, but _babel-root-import_ do not, because of its name.

Why this plugin wasn't named in common convention? Don't you think it would be better to rename the plugin?

For example, we've got this issue https://github.com/brunch/brunch/issues/1549 in [Brunch](http://brunch.io/). Of course, issue will be fixed by our efforts, but wouldn't it be easier for users not to write `babel-root-import`, but just `root-import`, every time they want to use your plugin?

**Comment by michaelzoidl** [comment]
I developed this plugin a while ago where this kind of standard wasn't that popular.
But i see your idea and i think it would be a better naming.. 
I'm wondering which side-effects this would have if rename this repo. 

And i've seen that the name is already taken on npm :/ 
https://github.com/andrelom/babel-plugin-root-import

**Comment by denysdovhan** [comment]
@michaelzoidl you can contact @andrelom and resolve this problem together.

Actually, I had experience in renaming packages — that's not so hard. You can deprecate old package and leave a message with link to the new one.

**Comment by andrelom** [comment]
Hi!

I am willing to remove/rename (deprecate) my NPM package in favor of the current one. Just send the instructions and I'll do it as soon as possible.

Sorry for the inconvenience.

**Comment by denysdovhan** [comment]
@andrelom you need to give @michaelzoidl an access to your package. Then just update corresponding `package.json`'s fields and publish. Package with old plugin name should be deprecated. 

P.S: I think it's better to bump major version with renaming a package.

**Comment by sivael** [comment]
Major version bumps should be done with breaking functionality. Unsure if this constitutes one but i don't think so.

**Comment by denysdovhan** [comment]
@sivael correct! But let's keep in mind that these two plugins may work a little bit different. Make sure, that you don't break anything. Be careful.

From my experience, it was better to bump major.

**Comment by sivael** [comment]
Oh. Did not connect the two facts. Yes then it has to be done.
Thanks for clarifying.

**Comment by michaelzoidl** [comment]
Ok guys, i'm back.. sorry for the 26 days waiting :S 

@andrelom awesome, if you can remove your package from npm i will move this repo to an organisation, rename it and publish it on your version.

I will bump the version to v5, i also add a information part in the repo - and add a note to the old `babel-root-import` npm package that we changed the name

Again, thank you guys for contributing to this

**Comment by andrelom** [comment]
Hi @ michaelzoidl, I added you as a contributor in the package, so you can publish the current package and deprecate the old one. I've tried deleting a package before, and after all, they ask to transfer the ownership to the NPM and depreciate the package. So I believe that is the easiest way to solve this.

**Comment by michaelzoidl** [comment]
Ok, after a year waiting I did it.. really..
Okay so i moved everything to the organisation i'm working for and renamed the package, i also bumped the version to 5.0.0 and published everything with the new name on [npm](https://www.npmjs.com/package/babel-plugin-root-import)

I think i can close this ticket now :)
