### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Luncher** [entwicklerstube/babel-plugin-root-import#65]
configure: 

  plugins: [
      ["babel-plugin-root-import", {
      "rootPathPrefix": "~",        
      "rootPathSuffix": "../src"
    }]
  ]

code:

`base.js`

```javascript
'use strict';

import Base from '~/common/controller/';

export default class extends Base {
  // async getAction() {
  //   let ret;

  //   ret = await super.getAction();
  //   this.success(ret);
  // }
}
```

---

`controller/index.js`

```javascript
'use strict';


/**
 *  Base Restful controller
 */

export default class extends think.controller.rest {

```

**error message**:

```
[2017-02-14 11:11:28] [Error] /Users/luncher/work/admin-plus/src/common/controller/index.js:8
export default class extends think.controller.rest {
^^^^^^
SyntaxError: Unexpected token export
```

**Comment by Luncher** [comment]
This is because this plugin does not support es6?

**Comment by michaelzoidl** [comment]
Seem's like you've not installed the [`babel-preset-es2015`](https://www.npmjs.com/package/babel-preset-es2015), since the `import` feature is not implemented in the default babel-preset (it's not a confirmed standard yet)

Install / add this package and try again :)

**Comment by Luncher** [comment]
I have already loaded the plugin, but it is still suggesting that this error.

**Comment by Guatom** [comment]
Just as a workaround, you could try to change `export default` to `module.exports =`.

**Comment by AnthonyNahas** [comment]
i have recently resolved a similar issue. Please take a look of my solution [here](https://github.com/SebastianM/angular-google-maps/issues/1052)
