### ISSUE TITLE
Converting from 3.2.2 to 5.0.0

### ISSUE THREAD

**Issue by adrianmcli** [entwicklerstube/babel-plugin-root-import#66]
I'm trying to convert [this resolver](https://github.com/olalonde/eslint-import-resolver-babel-root-import/pull/6) to use the updated version of `babel-plugin-root-import`. Inside the source code for that project, it uses the `transformRelativeToRootPath` helper function from `babel-plugin-root-import`.

Unfortunately, it seems the behaviour has changed significantly. The old behaviour does not match the new behaviour; Please see below.

## Reproduction

I'm running this:

```js
const transformedSource = transformRelativeToRootPath(source, rootPathSuffix, rootPathPrefix)
```

### Old behaviour `3.2.2`:

```
INPUT
-----
source: "@/file"
rootPathPrefix: "@"
rootPathSuffix: "/test/somepath"

OUTPUT
------
transformedSource: "/Users/adrianli/dev/eslint-import-resolver-babel-root-import/test/somepath/file"
```

### New behaviour `5.0.0`

```
INPUT
-----
source: "@/file"
rootPathPrefix: "@"
rootPathSuffix: "/test/somepath"

OUTPUT
------
transformedSource: "../../../../test/somepath/file"
```

## Question

What do I have to do with the inputs to get the desired (old) behaviour? Or is there another way I can get this to point to the correct file?

**Comment by adrianmcli** [comment]
@nescalante Your PR #44 seems to have caused a change in the internal API that this other resolver depends on. If you don't mind, could you take a look at what I need to change to make this work? I would love to upgrade the dependency to the new one so we can make use of your code.

I am having trouble getting this to work.

**Comment by nescalante** [comment]
To get the old behavior use the old version. What is the problem with the new one?
