### ISSUE TITLE
stopped working with react-native 0.43.3

### ISSUE THREAD

**Issue by jasan-s** [entwicklerstube/babel-plugin-root-import#73]
I'm calling it like so: `import { SplashContainer, FooterTabsContainer, SettingsContainer } from '~/containers'
` it should be reading from directory `/Users/jasan/Desktop/ReactModoro/app/containers `
It seems to add `app/containers/Navigator` in the path before

my babel rc file:
```
{  "presets": [
    "react-native-stage-0"
    ],
  "plugins": [
    ["babel-root-import", {
    "rootPathSuffix": "app"
    }]
  ]}
```

![screenshot_2017_04_16_20_18_22](https://cloud.githubusercontent.com/assets/13863953/25072858/2586edcc-228e-11e7-92b7-f41a27ed2fe9.png)

**Comment by jasan-s** [comment]
react-native start --reset-cache solved it

**Comment by michaelzoidl** [comment]
Ok cool, thanks for commenting the solution :)

**Comment by ryanhomer** [comment]
Also, if you are having similar path issues with your Jest tests, see [Jest cache incorrectly resolving modules](https://github.com/facebook/jest/issues/4092) on how to clear the Jest cache.

**Comment by sintylapse** [comment]
@jasan-s I'm getting this error every time, when I don't use --reset-cache postfix. Did you face this problem too?
