### ISSUE TITLE
[FIXED] Problems with "rootPathSuffix" 

### ISSUE THREAD

**Issue by BennyHoang** [entwicklerstube/babel-plugin-root-import#74]
Hi, 
i am trying to use this wonderful plugin, but are having problems with defining root folder. I get this error message when i add it: _provided an invalid property of "rootPathSuffix"_ 

And this is how my .babelrc file looks like

{
  "presets": ["react", "es2015", "stage-2"],
  "plugins": ["babel-plugin-root-import", {"rootPathSuffix": "src"}]
}

did i do something wrong here ?

**Comment by natew** [comment]
src does not work for some strange reason, any other name does. I ran into this and was really confusing!

**Comment by NoelBroda** [comment]
So this was the issues that I removed the plugin.

Remember that the app `create-react-app` create a `src` folder by default.

**Comment by BennyHoang** [comment]
I think it was because of the syntax. It works for me now. 
`  "plugins": [
    [
      "babel-plugin-root-import",
      [
        {
          "rootPathPrefix": "~"
        },
        {
          "rootPathPrefix": "*",
          "rootPathSuffix": "src"
        }
      ]
    ]
  ]`

**Comment by natew** [comment]
I'll try but I doubt it. One, logically it doesn't read like how I'd
expect. Two, it won't work with src but it does with any other name, why
would that be the case?

**Comment by brigand** [comment]
Confirmed this works in the current version.
