### ISSUE TITLE
Root paths are not correctly resolved with require.resolve.

### ISSUE THREAD

**Issue by andrewmunro** [entwicklerstube/babel-plugin-root-import#76]
babel-plugin-root-import correctly works with calls to `require` but not `require.resolve`. 

```
const foo = require('~/foo') // outputs as require('../../foo')
const pathToFoo = require.resolve('~/foo') // outputs as '~/foo'
```

**Comment by efranco2012** [comment]
As a temporary solution, I'm having to add a '.substring(5)' at the end of resolve() which removes the name of the actual 'src' folder/parent.  Ex: require.resolve('./../../img/symbol.svg').substring(5)
