### ISSUE TITLE
IDE support

### ISSUE THREAD

**Issue by degr** [entwicklerstube/babel-plugin-root-import#79]
Hello, anybody have experience with IDE support? Currently using IJ Idea, and it can't resolve paths. Of course, I need to know how to do it with IJ Idea, but absolutely sure that it will be useful, if somebody share his experience with eclipse or netbeans.

**Comment by flyingsky** [comment]
i postpone to use this plugin because of missing idea support. It cause two problems, first you cannot jump to definition, second missing auto prompt.

**Comment by musyoka-morris** [comment]
Same challenge here. 
Looking for a solution that has IDE support for autocompletion. More specifically PhpStorm|WebStorm

**Comment by degr** [comment]
I did not test this case, but from my opinion it should be possible with idea 2017.2 and more later versions, because they apply improved webpack support (https://blog.jetbrains.com/webstorm/2017/06/webstorm-2017-2-eap-172-2827/). Also, I'm not familiar with webpack (I use gulp), but webpack provide alias resolvers  (https://webpack.js.org/api/plugins/resolver/). I think that if you will use idea 2017.2, and if you will put webpack config into project (event without webpack) idea will use it for resolve. If I will have time to do this shit, I will reply about my progress, but I need to reinstall ide.

**Comment by kyawkyawsoezhu** [comment]
I'm using Webstorm, I don't know how to make IDE recognize `~`, so I use `/` as a prefix instead of `~`

**Comment by degr** [comment]
Guys, it work. As I write previously, IJ idea 2017.2.5 support webpack, and webpack support alias resolvers.
So, I use '~' character as my project root. 
I create this webpack.config.js file:
```javascript
const path = require('path');
module.exports = {
    entry: './index.js',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, './')
    },
    resolve: {
        alias: {
            root: path.join(__dirname, 'gulp/src/js/'),
            '~': path.resolve(__dirname, "gulp/src/js/"),
        }
    }
};
```
Then I just follow this article https://www.jetbrains.com/help/idea/webpack.html

And it start to resolve path. 
I have only one problem - 
import appDispatcher from "~/dispatcher/AppDispatcher";  < work perfectly
import appDispatcher from "~/dispatcher/AppDispatcher.js"; < not work

**Comment by m0onspell** [comment]
Not good. I am not using webpack in my project, nor any other bundler at all. 
Still lacking IDE support.

**Comment by brigand** [comment]
We have instructions for vscode in the readme, but I don't know intellij well enough to recommend a solution. 

@m0onspell I believe **`@degr`** was suggesting that you create a webpack config to appease intellij, even if you don't use it. 

I don't think that solution is clean enough to include in the readme. Closing this for now, but if anyone solves this, I'd very much like to add it to the readme.

**Comment by RossKinsella** [comment]
This helped me:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000507190-Cannot-Resolve-Imports-when-using-babel-resolver

**Comment by hannanstd** [comment]
Hi
i setted src as src. now webstorm works correclty without any configurations.

`	plugins: [
		[
			'babel-plugin-root-import',
			{
				paths: [
					{
						rootPathSuffix: 'src',
						rootPathPrefix: 'src',
					},
				],
			},
		],
	],`



example:
`import translations from 'src/translations';`
