### ISSUE TITLE
Won't work on .less or .scss?

### ISSUE THREAD

**Issue by eldyvoon** [entwicklerstube/babel-plugin-root-import#81]
It works fine with .js file but I got error of 

` Can't resolve './@/variables.less' `

This won't support .less or .scss?

**Comment by Aarbel** [comment]
same issue here

**Comment by eugene-kim** [comment]
This is a plugin for babel, a **Javascript** transpiler. Why would it support `less` or `scss`?

**Comment by Aarbel** [comment]
because babel is often coupled with webpack. And css imported  with javascript thanks to es6.

We resolved our problem using `babel-plugin-webpack-alias`

**extract of webpack.config**
```
    resolve: {
        alias: {
            'src': path.resolve(__dirname, './src'),
            'styles': path.resolve(__dirname, './src/style'),
        }
    },
```

**extract of a css file inside a component**
```
 @import 'styles/variables';

.arrowed {
    position: relative;
    background: inherit;
    border-radius: inherit;
    box-shadow: inherit;
    z-index: 0;
	…

```

**Comment by brigand** [comment]
Referring to .less/.scss files from JS code works but babel plugins are unable to transform the contents of .less/.scss files.
