### ISSUE TITLE
Not working with Jest

### ISSUE THREAD

**Issue by denghejun** [entwicklerstube/babel-plugin-root-import#88]
in some test file:
```
import ModuleProvider from '~/module.config'
```

get errors below:
```
Cannot find module '~/module.config' from 'app-bootstrapper.ts'
```

I have try to run jest with params `--no-cache`, still get the same error.

**Comment by shikelong** [comment]
+1 Not working with mocha

**Comment by brigand** [comment]
@shikelong please create a new issue with the error and steps to reproduce.

**Comment by Aequitas737** [comment]
@brigand what do you have to do to get it working with jest?

**Comment by brigand** [comment]
@Aequitas737 sorry for the late reply.

Aside from installing `babel-jest`, I don't think I do anything special. If you're having an issue, please explain in more detail (and error messages would help).

**Comment by witalobenicio** [comment]
This do not work with jest. All files we import using root-import are not recognized by jest.

**Comment by brigand** [comment]
@witalobenicio could you open a new issue with your babel config (specifying which file it's in) and package.json, along with the error you get?

**Comment by witalobenicio** [comment]
Yep @brigand . I've opened. Thanks.
