### ISSUE TITLE
Allow to access node_modules

### ISSUE THREAD

**Issue by vihanb** [entwicklerstube/babel-plugin-root-import#90]
If I have a module I want to import in `node_modules` like:

```js
import Dog from "animals/mammals/dog";
```

and I want to alias `~` to `animals/mammals`. So I can do `~/dog` is this possible?

doing: 

```js
{
    "rootPathPrefix": "~",
    "rootPathSuffix": "animals/mammals"
}
```

doesn't seem to work. I need to  set the suffix to  `node_modules/animals/mammals` but that's a yucky solution.

**Comment by brigand** [comment]
Paths like 'src' are supported, so this would be ambiguous.

(cleaning up issues)
