### ISSUE TITLE
Does not generate same paths on Mac and Windows

### ISSUE THREAD

**Issue by VincentCharpentier** [entwicklerstube/babel-plugin-root-import#94]
I'm working on a React Boilerplate: https://github.com/VincentCharpentier/boilerplate-react
I've seen my build and run tasks fail because of relative paths generated by babel-plugin-root-import.

this plugin is configured in .babelrc file like so:

    ["babel-plugin-root-import",
      {
        "rootPathSuffix": "shared"
      }
    ]

So `~/something` should lead to `${projectRoot}/shared/something`

On MacOS (10.13.2) everything is fine and the plugin do the job. However, on Windows (10) it fails.

# Server-side error
The server is started with `npm run start` (or `start:local`). The first file to be called is `${projectRoot}/server/server.js`

It resolves `~/router/MainRouter` to `${projectRoot}/server/shared/router/MainRouter` instead of `${projectRoot}/shared/router/MainRouter`

So I get this error:
> Error: Cannot find module './shared/router/MainRouter'

# Build-time error
The build operation is started with  `npm run build` (or `build:local`). The first file to be called is `${projectRoot}/client/client.js`

It resolves `~/router/MainRouter` to `${projectRoot}/client/shared/router/MainRouter` instead of `${projectRoot}/shared/router/MainRouter`.

So I get this error:
> Module not found: Error: Can't resolve './shared/router/MainRouter' in 'C:\www\boilerplate-react\client'

___

For what I understand with these errors is that the directory of my first file (client or server) is considered as the root directory of my project, which is wrong.

Do you have any suggestions to fix this without breaking any other features ?

Thank you for your time and help

**Comment by VincentCharpentier** [comment]
Note: If someone is able to point out what the bug might be I can try to fix it myself and send a PR

**Comment by VincentCharpentier** [comment]
this may be related to this past issue: https://github.com/entwicklerstube/babel-plugin-root-import/issues/10 ("fail on windows [after update to babel 6]

My project is running the babel 7.0.0-beta.32

**Comment by VincentCharpentier** [comment]
So I found the root cause of the issue.

It's in `transformRelativeToRootPath` function. On windows, variable `sourceFile` is `C:\[...]\file.js`

To get the source directory it looks for the last '/' (which isn't present on windows):

    var sourcePath = sourceFile.substring(0, sourceFile.lastIndexOf('/')); // => empty string

Using slash on sourcePath solved the issue for server-side execution. However I still have an error at build-time (webpack), I'm still struggling with it (any help/hints would be much appreciated)

Once everything is fixed I will send a PR

**Comment by brigand** [comment]
I believe this is fixed now, but I'm unable to test.
